# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Hevelian/build-tools/.github/workflows/maven-deploy.yml@feature/reusable-workflow
