# This workflow will build a package using Maven and then publish it to the OSS Sonatype repository when a release is created
name: Maven Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Hevelian/build-tools/.github/workflows/maven-deploy.yml@feature/reusable-workflow
    with:
      java-version: '17'
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
